"""Bridge to agentbastion: turn scan findings into a tool policy.

Closes the trilogy loop the same way bastionprobe/bastiontrace `harden` do:
a scan of an MCP server produces an agentbastion `policy.yaml` (default-deny,
clean tools allowed, risky tools denied) you drop straight into the firewall
or, next, into BastionGate.
"""

from __future__ import annotations

from .models import ScanReport

_BLOCK = {"critical", "high"}


def to_policy_yaml(report: ScanReport, tools: tuple) -> str:
    """tools: the Server.tools that were scanned (for the full name list)."""
    risky = {f.tool for f in report.findings if f.severity in _BLOCK and f.tool}
    all_names = [t.name for t in tools]
    allow = [n for n in all_names if n not in risky]
    deny = sorted(risky)

    lines = [
        f"# agentbastion tool policy generated by bastionsupply",
        f"# server: {report.server}  risk={report.risk}",
        "default: deny",
    ]
    lines.append("allow:")
    for n in allow:
        lines.append(f"  - {_q(n)}")
    if deny:
        lines.append("deny:")
        for n in deny:
            lines.append(f"  - {_q(n)}")
    return "\n".join(lines) + "\n"


def _q(name: str) -> str:
    """Quote a tool name for YAML if it isn't a plain identifier."""
    if name and all(c.isalnum() or c in "_-." for c in name):
        return name
    return '"' + name.replace("\\", "\\\\").replace('"', '\\"') + '"'
