"""Bridge to agentbastion: turn scan findings into a tool policy.

Closes the trilogy loop the same way bastionprobe/bastiontrace `harden` do:
a scan of an MCP server produces an agentbastion `policy.yaml` (default-deny,
clean tools allowed, risky tools denied) you drop straight into the firewall
or, next, into BastionGate.
"""

from __future__ import annotations

from .models import ScanReport

_BLOCK = {"critical", "high"}


_RATE_LIMIT = 10  # cautious per-session cap suggested for sensitive tools


def to_policy_yaml(report: ScanReport, tools: tuple) -> str:
    """tools: the Server.tools that were scanned (for the full name list).

    Beyond allow/deny, allowed-but-sensitive tools (a `sensitive-capability`
    finding that wasn't severe enough to deny) get graded caution: a
    `rate_limits` hint for agentbastion and a per-tool `scrub_results` override
    for bastiongate.
    """
    risky = {f.tool for f in report.findings if f.severity in _BLOCK and f.tool}
    all_names = [t.name for t in tools]
    allow = [n for n in all_names if n not in risky]
    deny = sorted(risky)
    # allowed tools that still expose a sensitive capability -> caution, not deny
    caution = sorted({
        f.tool for f in report.findings
        if f.check == "sensitive-capability" and f.tool and f.tool not in risky
    })

    lines = [
        "# agentbastion / bastiongate tool policy generated by bastionsupply",
        f"# server: {report.server}  risk={report.risk}",
        "default: deny",
        "allow:",
    ]
    lines += [f"  - {_q(n)}" for n in allow]
    if deny:
        lines.append("deny:")
        lines += [f"  - {_q(n)}" for n in deny]
    if caution:
        lines.append("rate_limits:  # agentbastion: cap sensitive tools per session")
        lines += [f"  {_q(n)}: {_RATE_LIMIT}" for n in caution]
        lines.append("tools:  # bastiongate: scrub secrets in sensitive tool results")
        for n in caution:
            lines.append(f"  {_q(n)}:")
            lines.append("    scrub_results: true")
    return "\n".join(lines) + "\n"


def _q(name: str) -> str:
    """Quote a tool name for YAML if it isn't a plain identifier."""
    if name and all(c.isalnum() or c in "_-." for c in name):
        return name
    return '"' + name.replace("\\", "\\\\").replace('"', '\\"') + '"'
